### ISSUE TITLE
Latest (epicpaladins-0.1.0-1.20.1-forge_light.jar) causing Domum-Ornamentum to not work

### ISSUE THREAD

**Issue by SenpaiDerp** [VeroxUniverse/EpicPaladins2.0-Forge#4]
Hello!

This mod was recently updated and used in the pack MineColonies Dimensional Adventure. After the update, it caused the Architect Table in Domum-Ornamentum to stop allowing inputs. I was told that you are aware of the issue, so I wanted to open an 'issue' for others that may have noticed the problem as well and are struggling.

Thanks!

**Comment by Moobien** [comment]
This issue is still happening.

**Comment by VeroxUniverse** [comment]
The mod is no longer under development sorrry
